<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <WarningsAsErrors>Nullable</WarningsAsErrors>
    <Authors>Michael Looper</Authors>
    <Company>Michael Looper</Company>
  </PropertyGroup>
</Project>
