<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<AssemblyName>PilotMcpServer</AssemblyName>
		<RootNamespace>PilotMcpServer</RootNamespace>
		<InvariantGlobalization>true</InvariantGlobalization>
	</PropertyGroup>

	<ItemGroup>
		<EmbeddedResource Include="appsettings.json" />
	</ItemGroup>

	<PropertyGroup>
		<PublishSingleFile>true</PublishSingleFile>
		<UseAppHost>true</UseAppHost>
	</PropertyGroup>
	
	<ItemGroup>
		<PackageReference Include="ModelContextProtocol.AspNetCore" />
		<PackageReference Include="Microsoft.Extensions.Hosting" />
	</ItemGroup>

</Project>
