using System.Text.Json.Serialization;

namespace PilotMcpServer.Models;

/// <summary>
/// RFC 7807 problem-details payload returned by a Pilot API on a 400 (or similar) response.
/// </summary>
public sealed class ProblemDetailsResponse
{
	/// <summary>
	/// A URI reference that identifies the problem type. This specification encourages that, when dereferenced, it provide human-readable documentation for the problem type (e.g., using HTML). When this member is not present, its value is assumed to be "about:blank".
	/// </summary>
	[JsonPropertyName("type")]
	public string? Type { get; init; }

	/// <summary>
	/// A short, human-readable summary of the problem type. It should not change from occurrence to occurrence of the problem.
	/// </summary>
	[JsonPropertyName("title")]
	public string? Title { get; init; }

	/// <summary>
	/// The HTTP status code generated by the origin server for this occurrence of the problem.
	/// </summary>
	[JsonPropertyName("status")]
	public int? Status { get; init; }

	/// <summary>
	/// A human-readable explanation specific to this occurrence of the problem.
	/// </summary>
	[JsonPropertyName("detail")]
	public string? Detail { get; init; }

	/// <summary>
	/// A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced.
	/// </summary>
	[JsonPropertyName("instance")]
	public string? Instance { get; init; }
}
